name: Events Demo 1
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'dev-*' # Matches branches like dev-1, dev-2, etc.
      - 'feat-**' # Matches branches like feat-1, feat-2, etc.

  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # Matches branches like dev-1, dev-2, etc.
      - 'feat-**' # Matches branches like feat-1, feat-2, etc.

    paths-ignore:
      - 'github/workflows/*' # Ignore changes to workflow files
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."